export const data = [
  {
    lightBg: false,
    primary: true,
    imgStart: "",
    lightTopLine: true,
    lightTextDesc: true,
    lightText: true,
    topLine: "Project #1",
    headline: "E-Commerce Platform",
    description:
      "An ecommerce platform designed with styled components using React for the front end. The backend consists of a Node.js server that also uses firebase as the database and authentication method",
    liveDemoBtn: "Demo",
    demoLink: "/sign-up",
    sourceCodeLink: "/sign-up",
    sourceCodeBtn: "Code",
    start: "",
    img: require("../../assets/tech-img.svg").default,
    alt: "image",
  },
  // {
  //   lightBg: true,
  //   primary: true,
  //   imgStart: "start",
  //   lightTopLine: false,
  //   lightTextDesc: false,
  //   lightText: false,
  //   topLine: "Project #2",
  //   headline: "More quick details about project, maybe what tech I used",
  //   description:
  //     "Some boring text about helping business owners increase revenue. This is some random text. Lorem ipsum is boring",
  //   liveDemoBtn: "Demo",
  //   sourceCodeBtn: "Code",
  //   demoLink: "/sign-up",
  //   sourceCodeLink: "/sign-up",
  //   start: "true",
  //   img: require("../../assets/profile-img.jpg"),
  //   alt: "image",
  // },
  // {
  //   lightBg: false,
  //   primary: true,
  //   imgStart: "",
  //   lightTopLine: true,
  //   lightTextDesc: true,
  //   lightText: true,
  //   topLine: "Project #3",
  //   headline: "More project details",
  //   description:
  //     "Some boring text about helping business owners increase revenue. This is some random text. Lorem ipsum is boring",
  //   liveDemoBtn: "Demo",
  //   sourceCodeBtn: "Code",
  //   demoLink: "/sign-up",
  //   sourceCodeLink: "/sign-up",
  //   start: "",
  //   img: require("../../assets/tech-3.svg").default,
  //   alt: "image",
  // },
  // {
  //   lightBg: true,
  //   primary: true,
  //   imgStart: "start",
  //   lightTopLine: false,
  //   lightTextDesc: false,
  //   lightText: false,
  //   topLine: "Current Project",
  //   headline: "Last project details",
  //   description:
  //     "Some boring text about helping business owners increase revenue. This is some random text. Lorem ipsum is boring",
  //   liveDemoBtn: "Demo",
  //   sourceCodeBtn: "Code",
  //   demoLink: "/sign-up",
  //   sourceCodeLink: "/sign-up",
  //   start: "true",
  //   img: require("../../assets/tech-2.svg").default,
  //   alt: "image",
  // },
];
